Remove models from gridt_server/resources files
GridtNetwork/gridt-server pull request #99
Opened 2020-11-10 20:20 UTC by mehfluffy

Partially solves Issue #93.

Fixed files in [gridt_server/resources](https://github.com/GridtNetwork/gridt-server/tree/GridtLibIncorporation/web/gridt_server/resources) by removing their dependency on `gridt_server.models`.

In helpers.py, deleted functions that depended on `gridt_server.models` but were never used anywhere else. 

In user.py, also deleted other unnecessary imports namely `jwt` and `util.email_templates` (lines 15-19). After using `gridt.controllers` instead (in the class `ResetPasswordResource`), all the above imports were no longer needed and were deleted.

2020-11-11 09:26 UTC, Drvanon commented
You have seemed to have removed the right stuff. Now please also remove the stuff from the tests.

2020-11-24 16:21 UTC, PJvanVliet requested changes
On the whole, I think a little bit too much was removed. Before merging, you should probably restore the tests that do not explicitly use models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -    def test_movement_schema_long(self):
Most tests here do not use models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -            user = self.create_user()
This test does use models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -    def test_change_email_schema_correct(self):
This test also uses models

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -    def test_change_email_schema_token_expired(self):
This test also uses models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -    def test_request_email_change_schema_correct(self):
So does this one.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/integration/resources/test_register.py
> -    def test_registration(self):
This test does not use models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/base_test.py
> -class BaseTest(LoggedTestCase):
You'll want to keep this. Without it, we cannot run tests. There are a few functions that are not able to remain due to their reliance on models.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/tests/base_test.py
> -    def tearDown(self):
All functions from here down rely on the database / models. They can no longer be used.

2020-11-24 16:21 UTC, PJvanVliet commented on web/gridt_server/resources/user.py
> +        reset_password(data["token"], data["password"], secret_key)
This indeed seems the correct way to call the gridtlib.

2020-11-24 16:22 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
> -            user = self.create_user()
Forgive my sloppy review. Here, I mean that removing this is fine. In SchemasTest, you should probably restore the tests that do not rely on models.

2020-11-24 19:40 UTC, mehfluffy commented
Indeed I have removed way too many things, I have now reset my head to 6c5a1fe and branched from there to work on removing models from the tests and rewriting them for Issue #97.

2020-11-24 21:08 UTC, mehfluffy commented
Since I didn't do much for Issue #97 yet, I will keep them somewhere and now focus on restoring the files and deleting the tests that @PJvanVliet mentioned on branch 93.

2020-11-28 10:14 UTC, PJvanVliet commented on web/gridt_server/tests/base_test.py
> -class BaseTest(LoggedTestCase):
Actually, all functions here rely on models.

2020-12-08 12:51 UTC, mehfluffy commented
With ada196e I also updated the big comment on Issue #93 with info on the tests/integration/models and tests/unit/models tests

2020-12-08 12:56 UTC, PJvanVliet requested changes

2020-12-08 12:56 UTC, PJvanVliet commented on web/gridt_server/tests/unit/test_schemas.py
>  class SchemasTest(BaseTest):
We should fix this before moving on. We should keep tests that do not use models!

2020-12-08 14:37 UTC, PJvanVliet approved these changes

2023-05-02 10:11 UTC, closed without merging